### ISSUE TITLE
Upload the ontology to the Matportal repository

### ISSUE THREAD

**Issue by vemonet** [ProjectDebbie/Ontology_DEB#3]
Hi, there is a repository of ontology for Material Science that have been recently created: https://matportal.org

It could be interesting to add the DEBBIE ontology to this portal

This allows then people working in Material Science to more easily find your ontology, search concepts in it, perform annotations of text using your ontology concept

Matportal is part of the OntoPortal Alliance, a project to help deploying ontologies repositories for various domain (https://ontoportal.org/)

**Comment by ProjectDebbie** [comment]
What a brilliant initiative and long overdue, I just uploaded DEB to Matportal.org, will keep an eye on it, thank you for flagging it up.
